project:
  type: website
  output-dir: docs
  preview:
    port: 2894
  render:
    - "*.qmd"
    - "*.md"
  resources:
    - "assets/**"
    
execute:
  freeze: auto

website:
  title: "autotelic"
  favicon: "/assets/images/icon-512.png"
  site-url: "https://learn.jpmonteagudo.com"
  repo-url: "https://github.com/jpmonteagudo28/autotelic"
  reader-mode: false
  page-navigation: true
  
  google-analytics: "G-SM9D5VRX5P"

  twitter-card: 
    image: "/assets/images/icon-512.png"
    card-style: summary_large_image
    creator: "@jpPabl0"
    site: "@jpPabl0"

  open-graph: 
    image: "/assets/images/icon-512.png"
    locale: en_US
    
  navbar:
    left:
      - text: "r"
        href: learn/advanceR/index.qmd
      - text: "epi"
        href: learn/epi/index.qmd
      - text: "art"
        href: learn/art/index.qmd
            
        
    right:
      - icon: github
        aria-label: github
        href: https://www.github.com/jpmonteagudo28/autotelic
        rel: me
            
  
format:
  html:
    theme: 
      - html/jpm.scss
    grid: 
      body-width: 800px
      sidebar-width: 250px
      margin-width: 250px
      gutter-width: 2.0em
    toc: false
    highlight-style: a11y
    code-link: true

editor: visual
